### PR TITLE
Fix for the Python 2.6.5 dict-is-string problem.

### PR DESCRIPTION
**Pull request by olleolleolle**
And a note that the port option exists. And that Redis has a default port.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Hello williamsj!

My sysadmin was using the script, and had a little problem in that the dictionary was not recursively turned into useful data structures, so we end up with a string u'keys=254,somethingelse=hello'

We fetched the number_of_keys in a try/except clause, catching the TypeError and partitioning the string to have a the 254.

(On my Python, 2.6.6 (FreeBSD) it worked as intended.)

**Comment by williamsjj** [comment]
While I appreciate the patch, I can't replicate this problem on 2.6.5:

```$ /git/misc_scripts/redis_check.py  --server localhost --port 6379 --warn 500 --critical 600
OK: Redis is using 0MB of RAM. Days Up: 12, Clients: 1, Version: 2.0.1, Polling API: epoll, DB-15: 269 keys
$ python
Python 2.6.5 (r265:79063, Apr 16 2010, 13:57:41) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > ```
> > > ```

**Comment by olleolleolle** [comment]
```
$ ./redis_check.py  --server ix-stat05.int --port 6379  --warn 500 --critical 600
Traceback (most recent call last):
 File "./redis_check.py", line 114, in <module>
   db_key_count = db_key_count + ", DB-%s: %s keys" % (key[2:],
redis_stats[key]["keys"])
TypeError: string indices must be integers

$ uname -a
Linux ix-monitor 2.6.32-32-server #62-Ubuntu SMP Wed Apr 20 22:07:43 UTC 2011 x86_64 GNU/Linux

$ python -V
Python 2.6.5

Redis Python module: redis-2.4.4

Redis version: 2.2.8
```

**Comment by olleolleolle** [comment]
Problem solved, closing!

$ apt-cache show python-redis
Package: python-redis
Priority: optional
Section: universe/python
Installed-Size: 96
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Original-Maintainer: Chris Lamb lamby@debian.org
Architecture: all
Version: 0.6.1-1
10:09
i think i will remove this ubuntu package

THAT was the culprit.

**Pull request closed without merging**
